"""Default configuration values.

This module contains all default configuration values used when loading
the TMRL configuration.
"""

_DEFAULT_TMRL_CONFIG = {
    "RUN_NAME": "tmrl_run",
    "BUFFERS_MAXLEN": 500000,
    "RW_MAX_SAMPLES_PER_EPISODE": 1000,
    "RW_TEST_EPISODE_INTERVAL": 5,
    # Match TMRL competition: 10 deterministic eval runs per checkpoint signal.
    "RW_TEST_EPISODES_PER_EVAL": 10,
    "CUDA_TRAINING": True,
    "CUDA_INFERENCE": False,
    "VIRTUAL_GAMEPAD": True,
    "LOCALHOST_WORKER": True,
    "LOCALHOST_TRAINER": True,
    "PUBLIC_IP_SERVER": "0.0.0.0",
    "PASSWORD": "YourRandomPasswordHere",
    "TLS": False,
    "TLS_HOSTNAME": "default",
    "TLS_CREDENTIALS_DIRECTORY": "",
    "NB_WORKERS": -1,
    "WANDB_PROJECT": "tmrl",
    "WANDB_ENTITY": "tmrl",
    "WANDB_KEY": "YourWandbApiKey",
    "WANDB_GRADIENTS": False,
    "WANDB_DEBUG_REWARD": True,
    "WANDB_WORKER": True,
    "PLAYER_RUNS": {
        "ONLINE_INJECTION": False,
        "SOURCE_PATH": "",
        "CONSUME_ON_READ": True,
        "MAX_FILES_PER_UPDATE": 1,
        "DEMO_INJECTION_REPEAT": 1,
        "DEMO_SAMPLING_WEIGHT": 1.0,
        "DEMO_WEIGHT_DECAY_SAMPLES": 0,
        "DEMO_WEIGHT_DECAY_SLOWDOWN": 1.0,
    },
    "PORT": 55555,
    "LOCAL_PORT_SERVER": 55556,
    "LOCAL_PORT_TRAINER": 55557,
    "LOCAL_PORT_WORKER": 55558,
    "BUFFER_SIZE": 536870912,
    "HEADER_SIZE": 12,
    "MODEL": {
        "MAX_EPOCHS": 10000,
        "ROUNDS_PER_EPOCH": 100,
        "TRAINING_STEPS_PER_ROUND": 200,
        "MAX_TRAINING_STEPS_PER_ENVIRONMENT_STEP": 4.0,
        "ENVIRONMENT_STEPS_BEFORE_TRAINING": 1000,
        # Steps between weight broadcasts to workers. Too large => workers run with stale
        # policies and off-policy corrections suffer. Recommend 100-500 for typical 20 Hz
        # rollouts. Higher inference latency (e.g. EfficientNet) may need more frequent
        # updates or a larger act_buf_len (see RTGYM_CONFIG).
        "UPDATE_MODEL_INTERVAL": 200,
        "UPDATE_BUFFER_INTERVAL": 200,
        "SAVE_MODEL_EVERY": 0,
        "BEST_CHECKPOINT_CRITERION": "eval",
        # Hybrid best checkpoint: competition-style mean lap (worker) when enough
        # clean finishes, else median return_test.
        # Set false for legacy eval (mean finish time only, no crash rules).
        "BEST_CHECKPOINT_LAP_TIME": True,
        # Require this many successful finishes in an eval window for lap-based saving;
        # null defaults to RW_TEST_EPISODES_PER_EVAL (all runs must finish, no crashes).
        "BEST_CHECKPOINT_MIN_FINISHES": None,
        # TMRL test competition: seconds added to next finished lap after a crash;
        # 3 crashes = out.
        "COMPETITION_EVAL_CRASH_PENALTY_S": 10.0,
        "COMPETITION_EVAL_MAX_CRASHES": 3,
        "MEMORY_SIZE": 1000000,
        "BATCH_SIZE": 256,
        "BATCHES_PER_STEP": 1,
        "SCHEDULER": {"NAME": "", "T_0": 100, "T_mult": 2, "eta_min": 1.0e-6, "last_epoch": -1},
        "NOISY_LINEAR_CRITIC": False,
        "NOISY_LINEAR_ACTOR": False,
        "OUTPUT_DROPOUT": 0.0,
        "RNN_DROPOUT": 0.0,
        "CNN_FILTERS": [32, 64, 64, 64],
        "CNN_OUTPUT_SIZE": 256,
        "RNN_LENS": [1],
        "RNN_SIZES": [64],
        "API_MLP_SIZES": [256, 256],
        "API_LAYERNORM": True,
        "MLP_LAYERNORM": False,
        "USE_RESIDUAL_MLP": False,
        "RESIDUAL_MLP_HIDDEN_DIM": 256,
        "RESIDUAL_MLP_NUM_BLOCKS": 6,
        "RESIDUAL_MLP_NUM_BLOCKS_ACTOR": 0,
        "RESIDUAL_MLP_NUM_BLOCKS_CRITIC": 0,
        "USE_RESIDUAL_SOPHY": False,
        "USE_TRACK_CONV1D": True,
        "USE_SIMBAV2": False,
        "TRACK_ENCODER": "conv1d",
        "GNN_LAYERS": 3,
        "GNN_HIDDEN": 64,
        "BINARY_BRAKE": False,
        "USE_RNN": False,
        "RNN_HIDDEN_SIZE": 0,
        "USE_EFFICIENTNET": True,
        "USE_FROZEN_EFFNET": False,
        "FROZEN_EFFNET_EMBED_DIM": 256,
        "FROZEN_EFFNET_WIDTH_MULT": 0.5,
        "FROZEN_EFFNET_VARIANT": "xs",
        "FROZEN_EFFNET_USE_DW_STEM": False,
    },
    "ALG": {
        "ALGORITHM": "SAC",
        "LEARN_ENTROPY_COEF": False,
        "LR_ACTOR": 1.0e-5,
        "LR_CRITIC": 5.0e-5,
        "LR_ENTROPY": 3.0e-4,
        "GAMMA": 0.99,
        "POLYAK": 0.995,
        "TARGET_ENTROPY": -0.5,
        "ALPHA": 0.01,
        "REDQ_N": 10,
        "REDQ_M": 2,
        "REDQ_Q_UPDATES_PER_POLICY_UPDATE": 20,
        "TOP_QUANTILES_TO_DROP": 2,
        "QUANTILES_NUMBER": 1,
        "N_STEPS": 1,
        "CLIPPING_WEIGHTS": False,
        "CLIP_WEIGHTS_VALUE": 1.0,
        "ACTOR_WEIGHT_DECAY": 0.0,
        "CRITIC_WEIGHT_DECAY": 0.0,
        "NUMBER_OF_POINTS": 0,
        "POINTS_DISTANCE": 0.0,
        "SPEED_BONUS": 0.0,
        "SPEED_MIN_THRESHOLD": 0.0,
        "SPEED_MEDIUM_THRESHOLD": 0.0,
        "ADAM_EPS": 1.0e-8,
        "R2D2_REWIND": 0.5,
        "R2D2_NUM_SEQUENCES": 0,
        "R2D2_SEQUENCE_LENGTH": 0,
        "R2D2_BURN_IN": 0,
        "OPTIMIZER_ACTOR": "adam",
        "OPTIMIZER_CRITIC": "adam",
        "BETAS_ACTOR": [0.9, 0.999],
        "BETAS_CRITIC": [0.9, 0.999],
        "L2_ACTOR": 0.0,
        "L2_CRITIC": 0.0,
        "GRAD_CLIP_ACTOR": 1.0,
        "GRAD_CLIP_CRITIC": 1.0,
        "BACKUP_CLIP_RANGE": 100.0,
        "BC_LAMBDA": 0.0,
        "BC_LAMBDA_START": 1.0,
        "BC_LAMBDA_END": 0.01,
        "BC_ANNEAL_STEPS_START": 0,
        "BC_ANNEAL_STEPS_END": 2000000,
        "MIXED_PRECISION": True,
        "MIXED_PRECISION_DTYPE": "bfloat16",
        "USE_SDE": True,
        "LOG_STD_INIT": -3.0,
        "SDE_CLIP_MEAN": 2.0,
        "SDE_SAMPLE_FREQ": 100,
        "ENTROPY_FLOOR": 0.02,
        "ENTROPY_SCHEDULE": "learnable",
        "ENTROPY_COSINE_T0": 300,
        "ENTROPY_COSINE_TMULT": 1.5,
        "ENTROPY_COSINE_DECAY": 0.7,
        "PER_TD_ENABLED": False,
        "PER_TD_ALPHA": 0.6,
        "PER_TD_BETA": 0.4,
        "PER_TD_EPS": 1.0e-6,
        "IQN_N_STEER_BINS": 13,
        "IQN_EPSILON_START": 1.0,
        "IQN_EPSILON_END": 0.005,
        "IQN_EPSILON_DECAY_STEPS": 500000,
        "IQN_EPSILON_COSINE_T0": 50000,
        "IQN_EPSILON_COSINE_TMULT": 1.5,
        "IQN_EPSILON_COSINE_DECAY": 0.8,
        "IQN_TARGET_UPDATE_FREQ": 1000,
        "IQN_NUM_QUANTILES_TRAIN": 64,
        "IQN_NUM_QUANTILES_TARGET": 64,
        "IQN_NUM_QUANTILES_EVAL": 32,
        "IQN_N_COS": 64,
        "IQN_DUELING": True,
        "IQN_DOUBLE_DQN": True,
        "IQN_GRAD_CLIP": 10.0,
        "IQN_LR": 1.0e-4,
        "IQN_EXPLORE_REPEAT_STEPS": 4,
    },
}

_DEFAULT_ENV_CONFIG = {
    "SEED": 0,
    "MAP_NAME": "",
    "MIN_NB_ZERO_REW_BEFORE_FAILURE": 0,
    "MAX_NB_ZERO_REW_BEFORE_FAILURE": 0,
    "MIN_NB_STEPS_BEFORE_FAILURE": 0,
    "OSCILLATION_PERIOD": 0,
    "NB_OBS_FORWARD": 0,
    "CRASH_PENALTY": 0.0,
    "CRASH_COOLDOWN": 0,
    "CONSTANT_PENALTY": 0.0,
    "LAP_REWARD": 0.0,
    "LAP_COOLDOWN": 0,
    "CHECKPOINT_REWARD": 0.0,
    "END_OF_TRACK_REWARD": 0.0,
    "USE_IMAGES": True,
    "SLEEP_TIME_AT_RESET": 1.5,
    "IMG_HIST_LEN": 4,
    "WINDOW_WIDTH": 640,
    "WINDOW_HEIGHT": 480,
    "IMG_GRAYSCALE": True,
    "IMG_WIDTH": 64,
    "IMG_HEIGHT": 64,
    "LINUX_X_OFFSET": 64,
    "LINUX_Y_OFFSET": 70,
    "IMG_SCALE_CHECK_ENV": 1.0,
    "INIT_GAS_BIAS": 0.0,
    "OBS_SPEED_SCALE": 1.0,
    "OBS_TRACK_SCALE": 1.0,
    "REWARD_CONFIG": {
        "WALL_HUG_SPEED_THRESHOLD": 10.0,
        "WALL_HUG_PENALTY_FACTOR": 0.005,
        "PROXIMITY_REWARD_SHAPING": 0.1,
        "REWARD_SCALE": 3.0,
        "PROGRESS_REWARD_FULL_LAP": 100.0,
        "PROGRESS_REWARD_EXPONENT": 1.0,
        "SPEED_REWARD_WEIGHT": 0.0,
        "SPEED_REWARD_THRESHOLD_KMH": 50.0,
        "MAX_SPEED_KMH": 300.0,
        "SPEED_TERMINAL_SCALE": 0.0,
        "PROJECTED_VELOCITY_SCALE": 0.1,
        "SPEED_REWARD_EXPONENT": 1.0,
        "MAX_TRACK_WIDTH": 23.5,
        "BOUNDARY_PENALTY_WEIGHT": 2.0,
        "BOUNDARY_CRASH_PENALTY": 10.0,
        "REWARD_CLIP_FLOOR": 10.0,
        "TIME_BONUS_SCALE": 0.0,
        "CONDITIONAL_PENALTY_WHEN_BRAKING": False,
        "BRAKE_THRESHOLD": 0.3,
        "TRACK_LOOK_AHEAD_PCT": 0.0,
        "TRACK_POINT_SPACING_M": 0.0,
    },
}

_DEFAULT_RTXGYM_CONFIG = {
    "time_step_duration": 0.05,
    "start_obs_capture": 0.04,
    "time_step_timeout_factor": 1.0,
    # Number of recent actions appended to obs for RT-MDP (covers control delay).
    # For heavier feature extractors (e.g. EfficientNet), consider increasing to cover
    # larger effective delay (e.g. 30 ms inference vs 5 ms).
    "act_buf_len": 2,
    "reset_act_buf": True,  # Clear action buffer on env.reset() to avoid stale actions.
    "benchmark": False,
    "wait_on_done": True,
    "ep_max_length": 1000,
}

_DEFAULT_DEBUGGER_CONFIG = {
    "DEBUG_MODE": False,
    "CRC_DEBUG": False,
    "CRC_DEBUG_SAMPLES": 0,
    "PROFILE_TRAINER": False,
    "WANDB_DEBUG": True,
    "PYTORCH_PROFILER": False,
    "OBSERVATION_BOUNDS_CHECK": False,
}


def deep_merge_defaults(cfg: dict, default: dict) -> None:
    """In-place merge default into cfg; only fill missing keys."""
    for key, default_val in default.items():
        if key not in cfg:
            cfg[key] = default_val
        elif isinstance(default_val, dict) and isinstance(cfg[key], dict):
            deep_merge_defaults(cfg[key], default_val)
