#!/usr/bin/env bash

# evaluate a command multiple times in parallel
# usage:
#   agents-parallel 3 python -m agents run  '&>>' '$LOG_DIR/job_$i.txt'
#
# special bash strings e.g. `&>>` need to be quoted

set -e # exit in case somethings fails
# set -x

echo "Starting $1x \`${@:2}\`"  # echo the original command

for i in $(seq 1 $1); do
  eval ${@:2} &
done

for i in $(seq 1 $1); do wait -n; done
echo all processes exited successfully